language: python

install:
    - pip install .
    - pip install flake8
    - pip install pytest

script:
    - python --version
    - flake8 fcat/
    - flake8 scripts/
    - bash run_cli.sh
    - pytest tests/